---
- include_tasks: metasploit.yml
  tags:
    - exploitation
    - metasploit

- include_tasks: empire.yml
  tags:
    - exploitation
    - empire

- include_tasks: powersploit.yml
  tags:
    - exploitation
    - powersploit

- include_tasks: searchsploit.yml
  tags:
    - exploitation
    - searchsploit
    - exploitdb

- include_tasks: supertty.yml
  tags:
    - exploitation
    - supertty