- block:

  - name: 'xortool : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/xortool
      force: yes
      repo: https://github.com/hellman/xortool.git

  - name: 'Check xortool directory contents'
    command: ls -la /opt/xortool
    register: xortool_contents

  - debug:
      var: xortool_contents.stdout_lines

  - name: 'xortool : remove existing venv'
    file:
      path: /opt/xortool/.venv
      state: absent

  - name: 'xortool : create venv directory'
    file:
      path: /opt/xortool/.venv
      state: directory

  - name: 'Check Python 3 Installation'
    command: python3 --version
    register: python3_check
    ignore_errors: yes

  - set_fact:
      python3_installed: "{{ python3_check.rc == 0 }}"

  - name: 'xortool : initialise venv'
    shell: 'bash -lc "virtualenv -p python3 /opt/xortool/.venv"'
    when: python3_installed

  - name: 'xortool : install docopt'
    pip:
      name: docopt
      state: present
      virtualenv: /opt/xortool/.venv

  - name: 'xortool : run setup'
    shell: 'bash -lc "source /opt/xortool/.venv/bin/activate && pip3 install xortool"'
    args:
      chdir: /opt/xortool

  - name: 'xortool : install launcher'
    copy:
      dest: /usr/local/bin/xortool
      mode: 0755
      src: ../files/xortool.sh

  tags:
    - crypto
    - xortool
  become: yes
