---
- block:
  - name: 'golang : download golang 1.23.1 archive'
    get_url:
      url: https://go.dev/dl/go1.23.1.linux-amd64.tar.gz
      dest: /tmp/golang.tar.gz
    tags:
      - golang

  - name: 'golang : extract archive'
    unarchive:
      dest: /usr/local
      remote_src: yes
      src: /tmp/golang.tar.gz

  - name: 'golang : add golang directory to $PATH'
    lineinfile:
      insertafter: EOF
      line: export PATH=$PATH:/usr/local/go/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile

  - name: 'golang : setup $GOPATH'
    lineinfile:
      insertafter: EOF
      line: export GOPATH=/root/.go
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile

  - name: 'golang : setup $GOBIN'
    lineinfile:
      insertafter: EOF
      line: export GOBIN=$GOPATH/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile

  - name: 'golang : cleanup fragments'
    file:
      dest: /tmp/golang.tar.gz
      state: absent

  tags:
    - common
    - golang
    - gobuster
  become: yes
