---
- block:
    - name: 'packages : update apt cache'
      apt:
        update_cache: yes

    - name: 'packages : install common packages'
      apt:
        name:
          - awscli
          - build-essential
          - curl
          - git
          - gnupg2
          - libcurl4-openssl-dev
          - nano
          - nmap
          - openvpn
          - python3
          - python3-pip
          - python3-setuptools
          - smbclient
          - socat
          - software-properties-common
          - tar
          - ufw
          - unzip
          - vim
          - zip
          - zsh
          - python3-venv
        state: present

    - name: 'packages : create virtual environment'
      command: python3 -m venv /home/kali/venv  # Update the path here
      args:
        creates: /home/kali/venv  # Update the path here

    - name: 'packages : install pyopenssl in venv'
      command: /home/kali/venv/bin/pip install pyopenssl  # Update the path here

    - name: 'packages : install virtualenv under Python 2'
      command: /home/kali/venv/bin/pip install virtualenv  # Update the path here
  tags:
    - common
    - packages
  become: yes