# - block:

#     - name: 'Add RVM GPG key'
#       apt_key:
#         url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7BE3E5681146FD4F1A40EDA28094BB14F4E3FBBE'
#         state: present
#       become: true

#     - name: 'ruby : add rvm repository'
#       apt_repository:
#         repo: 'ppa:rael-gc/rvm'
#         state: present
#         update_cache: yes
#       become: true

#     - name: 'ruby : install rvm'
#       apt:
#         name: rvm
#         state: present
#       become: true

#     - name: 'ruby : install default ruby'
#       shell: '/bin/bash -lc "rvm install ruby"'
#       become: true

#   tags:
#     - common
#     - ruby
#     - metasploit
#     - snmp-check
#     - whatweb
#     - wpscan
#     - wpxf
